class FinancePageLocators:
    HEADER_BUTTON = "//header[@class='header-wrapper']//li[5]"
    TITLE_FINANCE = "//h1[contains(text(),'Лизинг на автомобили')]"
    SUBHEADING_FINANCE = "//p[@class='_p_nxrz7_86']"
    FORM_FINANCE = "//div[@class='_form_1mktb_1']"
    BUTTON_MARK = "(//button[@class='_selectBody_1ncj2_1'])[1]"
    # SELECT_MARK = "(//span[contains(text(),'Марка')]"
    BUTTON_MODEL = "(//button[@class='_selectBody_1r87r_1'])[2]"
    BUTTON_YEAR = "(//button[@class='_selectBody_1ncj2_1 _selectBodySelected_1ncj2_38'])[1]"
    TITLE_WITH_INFO = "//h2[@class='_h2_nxrz7_73']"
    CARD_CONTENT = "//article[@class='_card_16tsy_1']"
    BUTTON_APPLICATION_ONE = "(//button[@type='button'])[2]"
    CARD_INFO = "//div[@class='_cardInfo_16tsy_53']"
    BANNER = "(//div[@id='sidebar_desktop'])[1]"
